"""
Builder V2 — Enhanced PPT builder using the Rendering Engine + Layout Engine.

Key improvements over the original Builder:
  1. Uses declarative SlideSpec DSL instead of imperative python-pptx calls
  2. Gradient backgrounds (via XML manipulation)
  3. Auto-fit text sizing based on content length
  4. Smart layout positioning based on content density
  5. Shadow effects on card elements
  6. Content-aware column widths in two-column layouts
  7. Consistent element styling through the rendering pipeline

Architecture:
  Content/Design → SlideSpec (DSL) → Renderer → .pptx
  The SlideSpec is a serializable intermediate representation that
  could also be generated by an LLM coding model as structured JSON.
"""

from __future__ import annotations

import logging
from pathlib import Path

from slidecraft.agents.base import BaseAgent
from slidecraft.models import (
    DesignSpec,
    GeneratedImage,
    PresentationContent,
    PresentationPlan,
    SlideType,
)
from slidecraft.engine.elements import (
    ElementType,
    GradientSpec,
    GradientStop,
    Position,
    SlideElement,
    SlideSpec,
    PresentationSpec,
    TextStyle,
    ShapeStyle,
    title_element,
    subtitle_element,
    text_element,
    bullets_element,
    shape_element,
    image_element,
    divider_element,
)
from slidecraft.engine.layout import (
    compute_content_layout,
    compute_two_column_layout,
    compute_timeline_positions,
    SLIDE_W,
    SLIDE_H,
    MARGIN,
    CONTENT_TOP,
)
from slidecraft.engine.renderer import (
    render_presentation,
)

logger = logging.getLogger("slidecraft")


class BuilderV2Agent(BaseAgent):
    """Enhanced PPT Builder using the declarative rendering engine.

    Instead of directly calling python-pptx APIs, this builder:
      1. Converts content + design → SlideSpec (DSL)
      2. Passes SlideSpec through the Layout Engine (auto-positioning)
      3. Renders via the Rendering Engine (gradients, shadows, auto-fit)

    The SlideSpec intermediate representation can also be generated
    by an LLM coding model, enabling infinite layout flexibility.
    """

    name = "builder_v2"
    description = "增强版 PPT 构建师，使用声明式渲染引擎"

    @property
    def system_prompt(self) -> str:
        return "You are the enhanced PPT builder agent with advanced rendering."

    def build(
        self,
        plan: PresentationPlan,
        content: PresentationContent,
        design: DesignSpec,
        images: list[GeneratedImage],
        output_path: str,
    ) -> str:
        """Build the final .pptx using the rendering engine."""

        # Build the color lookup for the renderer
        colors = {
            "primary": design.colors.primary,
            "secondary": design.colors.secondary,
            "accent": design.colors.accent,
            "background": design.colors.background,
            "surface": design.colors.surface,
            "text_primary": design.colors.text_primary,
            "text_secondary": design.colors.text_secondary,
        }

        # Default gradient for dark themes
        bg_gradient = None
        if design.use_gradient_backgrounds:
            bg_gradient = GradientSpec(
                angle=225,
                stops=[
                    GradientStop(color=design.colors.background, position=0.0),
                    GradientStop(color=self._darken(design.colors.background, 0.3), position=0.5),
                    GradientStop(color=self._blend(design.colors.background, design.colors.primary, 0.15), position=1.0),
                ],
            )

        # Create lookups
        image_map = {img.slide_number: img for img in images}
        content_map = {sc.slide_number: sc for sc in content.slides}

        # Build SlideSpecs for each slide
        spec = PresentationSpec(
            title=plan.title,
            slide_width=design.slide_width_inches,
            slide_height=design.slide_height_inches,
        )

        for slide_outline in plan.slides:
            sn = slide_outline.slide_number
            sc = content_map.get(sn)
            img = image_map.get(sn)

            slide_spec = self._build_slide_spec(
                slide_outline.slide_type, plan, sc, design,
                img, colors, bg_gradient,
            )
            slide_spec.slide_number = sn
            spec.slides.append(slide_spec)

        # Render the complete presentation
        prs = render_presentation(
            spec,
            colors,
            title_font=design.fonts.title_font,
            body_font=design.fonts.body_font,
        )

        # Save
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        prs.save(str(out))
        logger.info(f"[{self.name}] Saved enhanced presentation to {out}")
        return str(out)

    # ── Color utilities ──────────────────────────────────────

    def _darken(self, hex_color: str, amount: float = 0.2) -> str:
        """Darken a hex color by a proportional amount."""
        h = hex_color.lstrip("#")
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        r = max(0, int(r * (1 - amount)))
        g = max(0, int(g * (1 - amount)))
        b = max(0, int(b * (1 - amount)))
        return f"#{r:02x}{g:02x}{b:02x}"

    def _blend(self, color1: str, color2: str, ratio: float = 0.5) -> str:
        """Blend two hex colors. ratio=0 → color1, ratio=1 → color2."""
        h1 = color1.lstrip("#")
        h2 = color2.lstrip("#")
        r1, g1, b1 = int(h1[0:2], 16), int(h1[2:4], 16), int(h1[4:6], 16)
        r2, g2, b2 = int(h2[0:2], 16), int(h2[2:4], 16), int(h2[4:6], 16)
        r = int(r1 + (r2 - r1) * ratio)
        g = int(g1 + (g2 - g1) * ratio)
        b = int(b1 + (b2 - b1) * ratio)
        return f"#{r:02x}{g:02x}{b:02x}"

    # ── Slide spec builders ──────────────────────────────────

    def _build_slide_spec(
        self, slide_type, plan, sc, design, img, colors, bg_gradient,
    ) -> SlideSpec:
        """Route to the appropriate spec builder by type."""
        builders = {
            SlideType.COVER: self._spec_cover,
            SlideType.TABLE_OF_CONTENTS: self._spec_toc,
            SlideType.SECTION_HEADER: self._spec_section,
            SlideType.CONTENT: self._spec_content,
            SlideType.TWO_COLUMN: self._spec_two_column,
            SlideType.IMAGE_FULL: self._spec_image_full,
            SlideType.IMAGE_TEXT: self._spec_image_text,
            SlideType.CHART: self._spec_chart,
            SlideType.COMPARISON: self._spec_comparison,
            SlideType.TIMELINE: self._spec_timeline,
            SlideType.QUOTE: self._spec_quote,
            SlideType.THANK_YOU: self._spec_thank_you,
        }
        build_fn = builders.get(slide_type, self._spec_content)

        spec = SlideSpec(
            layout_type=slide_type.value,
            background_color=colors["background"],
            background_gradient=bg_gradient,
        )

        build_fn(spec, plan, sc, design, img, colors)
        return spec

    # ══════════════════════════════════════════════════════════
    #  1. COVER
    # ══════════════════════════════════════════════════════════

    def _spec_cover(self, spec, plan, sc, design, img, colors):
        title_text = sc.title if sc else plan.title
        subtitle_text = sc.subtitle if sc else plan.subtitle

        # Premium gradient for cover
        spec.background_gradient = GradientSpec(
            angle=225,
            stops=[
                GradientStop(color=colors["background"], position=0.0),
                GradientStop(color=self._darken(colors["background"], 0.4), position=0.4),
                GradientStop(color=self._blend(colors["background"], colors["primary"], 0.25), position=1.0),
            ],
        )

        # Top accent bar
        spec.add(shape_element(
            "rectangle", 0, 0, SLIDE_W, 0.15,
            fill_color=colors["primary"],
        ))

        # Left accent stripe
        spec.add(shape_element(
            "rectangle", 0, 0.15, 0.08, SLIDE_H,
            fill_color=colors["accent"],
        ))

        # Decorative circle (background)
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=SLIDE_W - 3.5, top=SLIDE_H - 3.5, width=5, height=5),
            shape_type="oval",
            shape_style=ShapeStyle(fill_color=colors["surface"]),
            z_order=-1,
        ))

        # Title (auto-sized)
        spec.add(title_element(
            title_text,
            left=1.5, top=2.0, width=8, height=1.8,
            font_size=design.fonts.title_size_pt + 8,
            color=colors["text_primary"],
        ))

        # Subtitle
        if subtitle_text:
            spec.add(subtitle_element(
                subtitle_text,
                left=1.5, top=3.9, width=8, height=1.0,
                font_size=design.fonts.subtitle_size_pt,
                color=colors["text_secondary"],
            ))

        # Cover image
        if img and Path(img.image_path).exists():
            spec.add(image_element(img.image_path, left=9.0, top=1.5, width=3.8, height=3.8))

    # ══════════════════════════════════════════════════════════
    #  2. TABLE OF CONTENTS
    # ══════════════════════════════════════════════════════════

    def _spec_toc(self, spec, plan, sc, design, img, colors):
        # Top bar
        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))

        # Title
        spec.add(title_element(
            sc.title if sc else "目录", left=1.0, top=0.5,
            font_size=design.fonts.title_size_pt, color=colors["text_primary"],
        ))

        # Divider
        spec.add(divider_element(left=1.0, top=1.3, width=2.5, color=colors["primary"]))

        # TOC items
        sections = [
            s for s in plan.slides
            if s.slide_type not in {
                SlideType.COVER,
                SlideType.TABLE_OF_CONTENTS,
                SlideType.THANK_YOU,
            }
        ]

        y = 1.8
        for i, sec in enumerate(sections[:8], 1):
            # Number circle
            spec.add(SlideElement(
                element_type=ElementType.SHAPE,
                position=Position(left=1.2, top=y + 0.05, width=0.35, height=0.35),
                shape_type="oval",
                content=str(i),
                shape_style=ShapeStyle(fill_color=colors["primary"]),
                text_style=TextStyle(font_size=12, bold=True, color="#ffffff", alignment="center"),
            ))

            # Section title
            spec.add(text_element(
                sec.title, left=1.8, top=y, width=10, height=0.5,
                font_size=18, color=colors["text_primary"],
            ))
            y += 0.65

    # ══════════════════════════════════════════════════════════
    #  3. SECTION HEADER
    # ══════════════════════════════════════════════════════════

    def _spec_section(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        # Full-width colored band
        spec.add(shape_element(
            "rectangle", 0, 2.0, SLIDE_W, 3.5,
            fill_color=colors["primary"],
        ))

        # Part label
        if sc.subtitle:
            spec.add(text_element(
                sc.subtitle, left=1.5, top=1.4, width=5, height=0.5,
                font_size=14, color=colors["text_secondary"],
            ))

        # Section title (white on primary)
        spec.add(title_element(
            sc.title, left=1.5, top=2.8, width=10, height=1.5,
            font_size=design.fonts.title_size_pt + 4,
            color="#ffffff",
        ))

        # Bottom accent line
        spec.add(divider_element(left=1.5, top=5.3, width=3, color=colors["accent"]))

    # ══════════════════════════════════════════════════════════
    #  4. CONTENT (auto-layout)
    # ══════════════════════════════════════════════════════════

    def _spec_content(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        has_image = bool(img and Path(img.image_path).exists()) if img else False
        layout = compute_content_layout(
            metrics=None,
            has_image=has_image,
            slide_width=design.slide_width_inches,
        )

        # Top bar
        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))

        # Title
        spec.add(title_element(
            sc.title,
            left=layout["title"].left,
            top=layout["title"].top,
            width=layout["title"].width,
            height=layout["title"].height,
            font_size=design.fonts.title_size_pt,
            color=colors["text_primary"],
        ))

        # Text card
        content_pos = layout["content"]
        spec.add(shape_element(
            "rounded_rect",
            content_pos.left - 0.05,
            content_pos.top - 0.05,
            content_pos.width + 0.1,
            content_pos.height + 0.1,
            fill_color=colors["surface"],
            border_color=self._blend(colors["surface"], colors["primary"], 0.35),
            shadow=True,
        ))

        if sc.bullet_points:
            spec.add(bullets_element(
                sc.bullet_points,
                left=content_pos.left + 0.2,
                top=content_pos.top + 0.2,
                width=content_pos.width - 0.4,
                height=content_pos.height - 0.4,
                font_size=design.fonts.body_size_pt,
                color=colors["text_primary"],
            ))

        # Image
        if has_image:
            image_pos = layout["image"]
            spec.add(shape_element(
                "rounded_rect",
                image_pos.left - 0.05,
                image_pos.top - 0.05,
                image_pos.width + 0.1,
                image_pos.height + 0.1,
                fill_color=colors["surface"],
                border_color=self._blend(colors["surface"], colors["primary"], 0.35),
                shadow=True,
            ))
            spec.add(image_element(
                img.image_path,
                left=image_pos.left,
                top=image_pos.top,
                width=image_pos.width,
                height=image_pos.height,
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  5. TWO COLUMN (smart sizing)
    # ══════════════════════════════════════════════════════════

    def _spec_two_column(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))
        spec.add(title_element(sc.title, font_size=design.fonts.title_size_pt, color=colors["text_primary"]))

        points = sc.bullet_points or []
        mid = len(points) // 2 or 1
        left_items = points[:mid]
        right_items = points[mid:]

        # Smart layout: adjust column widths based on content balance
        layout = compute_two_column_layout(
            len(left_items), len(right_items),
            slide_width=design.slide_width_inches,
        )

        # Left card (with shadow)
        lp = layout["left_card"]
        spec.add(shape_element(
            "rounded_rect", lp.left, lp.top, lp.width, lp.height,
            fill_color=colors["surface"], shadow=True,
        ))
        if left_items:
            spec.add(bullets_element(
                left_items,
                left=lp.left + 0.3, top=lp.top + 0.3,
                width=lp.width - 0.6, height=lp.height - 0.6,
                font_size=design.fonts.body_size_pt, color=colors["text_primary"],
            ))

        # Vertical divider
        div_x = layout["divider_x"]
        spec.add(shape_element(
            "rectangle", div_x, CONTENT_TOP + 0.2, 0.03, 4.8,
            fill_color=colors["primary"],
        ))

        # Right card (with shadow)
        rp = layout["right_card"]
        spec.add(shape_element(
            "rounded_rect", rp.left, rp.top, rp.width, rp.height,
            fill_color=colors["surface"], shadow=True,
        ))
        if right_items:
            spec.add(bullets_element(
                right_items,
                left=rp.left + 0.3, top=rp.top + 0.3,
                width=rp.width - 0.6, height=rp.height - 0.6,
                font_size=design.fonts.body_size_pt, color=colors["text_primary"],
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  6. IMAGE FULL
    # ══════════════════════════════════════════════════════════

    def _spec_image_full(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        # Full-bleed image
        if img and Path(img.image_path).exists():
            spec.add(image_element(img.image_path, 0, 0, SLIDE_W, SLIDE_H))

        # Overlay band at bottom (gradient effect simulated)
        spec.add(shape_element(
            "rectangle", 0, SLIDE_H - 2.5, SLIDE_W, 2.5,
            fill_color=colors["background"],
        ))

        # Title on overlay
        spec.add(title_element(
            sc.title, left=1.0, top=SLIDE_H - 2.2, width=11, height=1.0,
            font_size=design.fonts.title_size_pt, color=colors["text_primary"],
        ))

        if sc.subtitle or sc.body_text:
            spec.add(text_element(
                sc.subtitle or sc.body_text,
                left=1.0, top=SLIDE_H - 1.2, width=11, height=0.8,
                font_size=design.fonts.body_size_pt, color=colors["text_secondary"],
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  7. IMAGE + TEXT
    # ══════════════════════════════════════════════════════════

    def _spec_image_text(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))
        spec.add(title_element(sc.title, font_size=design.fonts.title_size_pt, color=colors["text_primary"]))

        has_image = bool(img and Path(img.image_path).exists()) if img else False
        layout = compute_content_layout(
            metrics=None,
            has_image=has_image,
            slide_width=design.slide_width_inches,
        )

        if has_image:
            image_pos = layout["content"]
            spec.add(shape_element(
                "rounded_rect",
                image_pos.left - 0.05,
                image_pos.top - 0.05,
                image_pos.width + 0.1,
                image_pos.height + 0.1,
                fill_color=colors["surface"],
                border_color=self._blend(colors["surface"], colors["primary"], 0.35),
                shadow=True,
            ))
            spec.add(image_element(
                img.image_path,
                left=image_pos.left,
                top=image_pos.top,
                width=image_pos.width,
                height=image_pos.height,
            ))

        text_pos = layout["image"] if has_image else layout["content"]
        spec.add(shape_element(
            "rounded_rect",
            text_pos.left - 0.05,
            text_pos.top - 0.05,
            text_pos.width + 0.1,
            text_pos.height + 0.1,
            fill_color=colors["surface"],
            border_color=self._blend(colors["surface"], colors["primary"], 0.35),
            shadow=True,
        ))

        if sc.bullet_points:
            spec.add(bullets_element(
                sc.bullet_points,
                left=text_pos.left + 0.2,
                top=text_pos.top + 0.2,
                width=text_pos.width - 0.4,
                height=text_pos.height - 0.4,
                font_size=design.fonts.body_size_pt, color=colors["text_primary"],
            ))
        elif sc.body_text:
            spec.add(text_element(
                sc.body_text,
                left=text_pos.left + 0.2,
                top=text_pos.top + 0.2,
                width=text_pos.width - 0.4,
                height=text_pos.height - 0.4,
                font_size=design.fonts.body_size_pt, color=colors["text_primary"],
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  8. CHART
    # ══════════════════════════════════════════════════════════

    def _spec_chart(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))
        spec.add(title_element(sc.title, font_size=design.fonts.title_size_pt, color=colors["text_primary"]))

        if sc.data and "labels" in sc.data and "values" in sc.data:
            spec.add(SlideElement(
                element_type=ElementType.CHART,
                position=Position(left=1.0, top=1.6, width=11, height=5.2),
                chart_data=sc.data,
            ))
        elif sc.bullet_points:
            spec.add(bullets_element(
                sc.bullet_points, font_size=design.fonts.body_size_pt,
                color=colors["text_primary"],
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  9. COMPARISON
    # ══════════════════════════════════════════════════════════

    def _spec_comparison(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))
        spec.add(title_element(sc.title, font_size=design.fonts.title_size_pt, color=colors["text_primary"]))

        points = sc.bullet_points or []
        mid = max(len(points) // 2, 1)
        left_items = points[:mid]
        right_items = points[mid:]

        # Left card
        spec.add(shape_element("rounded_rect", 0.5, 1.6, 5.9, 5.3,
                               fill_color=colors["surface"], border_color=colors["primary"], shadow=True))
        # Left header
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=0.5, top=1.6, width=5.9, height=0.5),
            shape_type="rectangle",
            content="方案 A",
            shape_style=ShapeStyle(fill_color=colors["primary"]),
            text_style=TextStyle(font_size=16, bold=True, color="#ffffff", alignment="center"),
        ))
        if left_items:
            spec.add(bullets_element(left_items, left=0.8, top=2.4, width=5.3, height=4.2,
                                     color=colors["text_primary"]))

        # VS badge
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=6.15, top=3.5, width=1.0, height=1.0),
            shape_type="oval",
            content="VS",
            shape_style=ShapeStyle(fill_color=colors["accent"], shadow=True),
            text_style=TextStyle(font_size=16, bold=True, color="#ffffff", alignment="center"),
        ))

        # Right card
        spec.add(shape_element("rounded_rect", 6.9, 1.6, 5.9, 5.3,
                               fill_color=colors["surface"], border_color=colors["secondary"], shadow=True))
        # Right header
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=6.9, top=1.6, width=5.9, height=0.5),
            shape_type="rectangle",
            content="方案 B",
            shape_style=ShapeStyle(fill_color=colors["secondary"]),
            text_style=TextStyle(font_size=16, bold=True, color="#ffffff", alignment="center"),
        ))
        if right_items:
            spec.add(bullets_element(right_items, left=7.2, top=2.4, width=5.3, height=4.2,
                                     color=colors["text_primary"]))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  10. TIMELINE (auto-positioned)
    # ══════════════════════════════════════════════════════════

    def _spec_timeline(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        spec.add(shape_element("rectangle", 0, 0, SLIDE_W, 0.06, fill_color=colors["primary"]))
        spec.add(title_element(sc.title, font_size=design.fonts.title_size_pt, color=colors["text_primary"]))

        points = sc.bullet_points or []
        milestones = compute_timeline_positions(len(points), design.slide_width_inches)

        # Horizontal timeline bar
        spec.add(shape_element(
            "rectangle", MARGIN, 3.8, SLIDE_W - 2 * MARGIN, 0.06,
            fill_color=colors["primary"],
        ))

        for i, (point, ms) in enumerate(zip(points[:7], milestones)):
            dot_size = 0.35

            # Milestone dot
            spec.add(shape_element(
                "oval", ms["cx"] - dot_size / 2, ms["bar_y"] - dot_size / 2 + 0.03,
                dot_size, dot_size,
                fill_color=colors["primary"],
            ))

            # Inner dot
            spec.add(shape_element(
                "oval", ms["cx"] - 0.075, ms["bar_y"] - 0.045,
                0.15, 0.15,
                fill_color=colors["background"],
            ))

            # Label (alternating above/below)
            label_y = ms["label_y_above"] if ms["is_above"] else ms["label_y_below"]
            spec.add(text_element(
                point,
                left=ms["cx"] - ms["label_width"] / 2, top=label_y,
                width=ms["label_width"], height=1.2,
                font_size=design.fonts.caption_size_pt,
                color=colors["text_primary"], alignment="center",
            ))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  11. QUOTE
    # ══════════════════════════════════════════════════════════

    def _spec_quote(self, spec, plan, sc, design, img, colors):
        if not sc:
            return

        # Opening quotation mark
        spec.add(text_element(
            "\u201C", left=1.5, top=1.2, width=2, height=2,
            font_size=120, color=colors["primary"], alignment="left",
        ))

        # Quote text
        quote_text = sc.body_text or sc.title
        spec.add(SlideElement(
            element_type=ElementType.TEXT,
            position=Position(left=2.0, top=2.5, width=9.3, height=3.0),
            content=quote_text,
            text_style=TextStyle(
                font_size=28, italic=True,
                color=colors["text_primary"], alignment="center",
            ),
        ))

        # Attribution
        if sc.subtitle:
            spec.add(text_element(
                f"— {sc.subtitle}",
                left=2.0, top=5.0, width=9.3, height=0.6,
                font_size=18, color=colors["text_secondary"], alignment="center",
            ))

        # Closing quotation mark
        spec.add(text_element(
            "\u201D", left=10, top=4.5, width=2, height=2,
            font_size=120, color=colors["primary"], alignment="right",
        ))

        # Bottom accent
        spec.add(divider_element(left=5.5, top=5.8, width=2.3, color=colors["accent"]))

        if sc.notes:
            spec.notes = sc.notes

    # ══════════════════════════════════════════════════════════
    #  12. THANK YOU
    # ══════════════════════════════════════════════════════════

    def _spec_thank_you(self, spec, plan, sc, design, img, colors):
        # Decorative circles
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=-1, top=-1, width=4, height=4),
            shape_type="oval",
            shape_style=ShapeStyle(fill_color=colors["surface"]),
            z_order=-1,
        ))
        spec.add(SlideElement(
            element_type=ElementType.SHAPE,
            position=Position(left=SLIDE_W - 3, top=SLIDE_H - 3, width=5, height=5),
            shape_type="oval",
            shape_style=ShapeStyle(fill_color=colors["surface"]),
            z_order=-1,
        ))

        # Main text
        spec.add(title_element(
            sc.title if sc else "谢谢！",
            left=2, top=2.2, width=9.3, height=1.5,
            font_size=52, color=colors["primary"],
        ))
        # Override alignment to center
        spec.elements[-1].text_style.alignment = "center"

        if sc and sc.subtitle:
            spec.add(subtitle_element(
                sc.subtitle, left=2, top=3.8, width=9.3, height=0.8,
                font_size=24, color=colors["text_secondary"],
            ))
            spec.elements[-1].text_style.alignment = "center"

        # Accent line
        spec.add(divider_element(left=5.0, top=4.8, width=3.3, color=colors["primary"]))

        # Contact info
        if sc and sc.bullet_points:
            spec.add(bullets_element(
                sc.bullet_points[:3],
                left=3, top=5.3, width=7.3, height=1.5,
                font_size=14, color=colors["text_secondary"],
            ))
